function v12AudioUrl(url,clickOn){if(!url)return null;const parsed=new URL(url,window.location.href);parsed.searchParams.set("click",clickOn?"1":"0");return parsed.pathname+parsed.search+parsed.hash;}
function v12Anchor(result){const a=result?.clickAnchor;return a&&(a.available===true||a.status==="available")&&Array.isArray(a.slots)?a:null;}
function v12RecordedLabel(result){const value=result.recordedAt||result.finishedAt||result.createdAt;if(!value)return result.takeId?.slice(-8)||"시각 기록 없음";const date=new Date(value);return Number.isNaN(date.getTime())?"시각 기록 없음":date.toLocaleString("ko-KR",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false,timeZone:"Asia/Seoul"});}
function v12DeltaWords(value){const n=v2RoundFive(value);return n===null?"클릭과의 차이를 재지 못함":n===0?"클릭 부근 · 표시 0 ms":"클릭보다 "+Math.abs(n)+" ms "+(n<0?"앞":"뒤");}
function v12SourceWords(source){return ({r2:"r2의 시각",knee:"무릎의 시각",rho:"소리 변화 후보 시각 · 시작 시각 불명"})[source]||"시각 출처 확인 중";}
function v12OverallWords(result){const mean=v12Anchor(result)?.summary?.meanMs;if(!v21ResultCalibrationValid(result)||result?.monitorRoute!=="direct"||!v2Finite(mean))return null;return Math.abs(mean)<=10?"전체로는 클릭 부근에 놓였습니다":mean<0?"전체로 클릭보다 조금 앞에 놓였습니다":"전체로 클릭보다 조금 뒤에 놓였습니다";}
function v12SlotPlaybackRange(result,slot){const a=v12Anchor(result);if(!a)return null;const at=a.slots.findIndex(x=>x.index===slot.index);if(at<0)return null;const lo=a.slots[Math.max(0,at-2)].clickTimeSeconds,hi=a.slots[Math.min(a.slots.length-1,at+2)].clickTimeSeconds;const note=result.notes?.find(n=>n.index===slot.candidateId),neighbor=note?v2PlaybackRange(result,note):null;const start=Math.max(0,Math.min(lo-.15,neighbor?.startSeconds??Infinity));const end=Math.min(result.durationSeconds??Infinity,Math.max(hi+.4,neighbor?.endSeconds??-Infinity));return v2Finite(start)&&v2Finite(end)&&end>start?{startSeconds:start,endSeconds:end}:null;}
function v12FriendlyError(error){const message=String(error||"");if(!message)return "";if(/analysis-followup|analysis-worker|analysis-/.test(message))return "녹음은 저장했지만 분석 결과를 준비하지 못했습니다. 녹음은 보존되어 있습니다.";if(/device|endpoint|exclusive|open|audio|WASAPI/i.test(message))return "오디오 장치를 열거나 유지하지 못했습니다. 같은 인터페이스를 쓰는 다른 앱과 연결 상태를 확인해 주세요.";if(/timeout|clock|progress/i.test(message))return "녹음 진행 상태를 확인하지 못해 멈췄습니다. 저장 상태를 확인해 주세요.";if(/previous-attempt|unconfirmed|retry/i.test(message))return "이전 요청의 완료 상태를 확인하지 못했습니다. 자동으로 다시 녹음하지 않습니다.";return "프로그램 쪽 문제로 멈췄습니다. 장치와 지연 설정의 기록 내보내기를 보내 주세요";}
function v12CompletionKey(previous,next){const takeId=next?.lastSavedTakeId;return takeId&&["SAVED","ENDED"].includes(next.phase)?takeId:null;}
