function v23StepDefinition(session,index=session?.currentStepIndex){return session?.scriptSnapshot?.steps?.[index]||null;}
function v23StepState(session,index=session?.currentStepIndex){return session?.steps?.find(step=>step.index===index)||session?.steps?.[index]||null;}
function v23PendingRecords(snapshot){return (snapshot?.sessions||[]).flatMap(session=>(session.steps||[]).filter(step=>step.pendingRecord).map(step=>({sessionId:session.sessionId,stepIndex:step.index,recordRequestId:step.pendingRecord.requestId})));}
function v23TakeGate(snapshot,takeId){if(v23PendingRecords(snapshot).length)return {loading:true,takeId};const link=snapshot?.takeIndex?.[takeId];if(!link||link.viewedAt)return null;const session=snapshot.sessions?.find(item=>item.sessionId===link.sessionId);return {...link,takeId,session,definition:v23StepDefinition(session,link.stepIndex)};}
function v23StepLabel(session,index=session?.currentStepIndex){const step=v23StepDefinition(session,index);if(!step)return "단계 확인 중";const records=session.scriptSnapshot.steps.filter(item=>item.type==="record"),ordinal=records.indexOf(step);return step.type==="record"?(step.id||"T"+(ordinal+1))+"/"+records.length:step.type==="listen"?"함께 듣기":"마지막 질문";}
function v23RecordBinding(session,fields){
  if(!session||session.endedAt)return null;const definition=v23StepDefinition(session),step=v23StepState(session);
  if(fields.participant!==undefined&&fields.participant!==v24Participant(session))throw new Error("세션의 이름표와 지금 치는 사람이 다릅니다. 세션을 다시 열거나 일반 연습으로 전환해 주세요.");
  if(definition?.type!=="record")throw new Error("지금은 녹음 단계가 아닙니다. 일반 연습으로 전환하면 별도로 녹음할 수 있습니다.");
  if(step?.takeIds?.length)throw new Error("이 단계의 녹음이 있습니다. 다음 단계로 가거나 일반 연습으로 전환해 주세요.");
  if(fields.taskId!==definition.taskId||fields.bpm!==definition.bpm||fields.clickMode!==definition.clickMode)throw new Error("세션의 과제·빠르기·클릭과 다릅니다. 이 단계 열기를 누르거나 일반 연습으로 전환해 주세요.");
  return {sessionId:session.sessionId,stepIndex:session.currentStepIndex};
}
function v23StepComplete(session){const definition=v23StepDefinition(session),step=v23StepState(session);if(!definition||!step)return false;if(step.skipped)return true;if(definition.type==="record")return !!step.takeIds?.length&&(!(definition.beforeQuestions||[]).length||(step.takes||[]).every(take=>!!take.viewedAt));if(definition.type==="listen")return definition.slots.every(slot=>(step.listenAnswers||[]).some(answer=>answer.slot===slot));return Array.isArray(step.answers)&&step.answers.length===definition.questions.length;}
function v23ToggleUnstable(values,value,exclusiveOption="없음"){if(value===exclusiveOption)return values.includes(value)?[]:[value];const next=values.filter(item=>item!==exclusiveOption);return next.includes(value)?next.filter(item=>item!==value):[...next,value];}
function v23QuestionsBudget(session,answers){const bytes=new TextEncoder().encode(JSON.stringify({requestId:"00000000-0000-0000-0000-000000000000",sessionId:session.sessionId,stepIndex:session.currentStepIndex,answers})).length,limit=15000;return {bytes,limit,remaining:limit-bytes,allowed:bytes<=limit};}
function useV23Sessions(onError){
  const [snapshot,setSnapshot]=useState({sessions:[],active:null,takeIndex:{}}),[scripts,setScripts]=useState([]),[scriptErrors,setScriptErrors]=useState([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[hidden,setHidden]=useState(false),[summaryId,setSummaryId]=useState(null),[recordPending,setRecordPending]=useState(false);
  const latest=useRef(snapshot),live=useRef(true),lock=useRef(false),requests=useRef(new Map()),activeRef=useRef(null);latest.current=snapshot;activeRef.current=hidden?null:snapshot.active;
  const accept=value=>{if(!value||!Array.isArray(value.sessions)||!value.takeIndex||v2Finite(value.revision)&&v2Finite(latest.current.revision)&&value.revision<latest.current.revision)return;latest.current=value;if(live.current){setSnapshot(value);setReady(true);}};
  const get=async route=>{const response=await fetch("/api/"+route,{cache:"no-store",headers:{"X-Session-Token":window.__SESSION_TOKEN__||""}}),value=await response.json();v19ReloadForStaleToken(response,value);if(!response.ok)throw new Error(value.message||"세션 기록을 읽지 못했습니다. 다시 확인해 주세요.");return value;};
  const refresh=async()=>{const value=await get("sessions");accept(value);return value;};
  const acceptSession=session=>{if(!session)return;const old=latest.current,sessions=[session,...old.sessions.filter(item=>item.sessionId!==session.sessionId)],takeIndex={...old.takeIndex};for(const step of session.steps||[])for(const take of step.takes||[]){takeIndex[take.takeId]={...take,sessionId:session.sessionId,stepIndex:step.index,requiresBefore:!!v23StepDefinition(session,step.index)?.beforeQuestions?.length};}accept({...old,sessions,active:session.endedAt?(old.active?.sessionId===session.sessionId?null:old.active):session,takeIndex});};
  const action=async(type,fields={})=>{if(lock.current)return null;lock.current=true;setBusy(true);const key=type+":"+JSON.stringify(fields),requestId=requests.current.get(key)||crypto.randomUUID();requests.current.set(key,requestId);
    try{const response=await fetch("/api/sessions/"+type,{method:"POST",headers:{"Content-Type":"application/json","X-Session-Token":window.__SESSION_TOKEN__||""},body:JSON.stringify({requestId,...fields})}),value=await response.json();v19ReloadForStaleToken(response,value);if(!response.ok){requests.current.delete(key);throw new Error(value.message||"세션 기록을 저장하지 못했습니다. 다시 눌러 주세요.");}if(value.guidedSessions)accept(value.guidedSessions);else acceptSession(value.session);requests.current.delete(key);if(type==="start")setHidden(false);if(type==="end"){setSummaryId(value.session?.sessionId);setHidden(false);}return value.session;
    }catch(error){onError(error.message);return null;}finally{lock.current=false;if(live.current)setBusy(false);}};
  const recoverPending=async()=>{const current=await refresh();for(const pending of v23PendingRecords(current)){if(!await action("bind",pending))return false;}const value=await refresh();if(v23PendingRecords(value).length){onError("녹음 연결을 아직 확인하지 못했습니다. 프로그램을 다시 열어 복구해 주세요.");return false;}setRecordPending(false);return true;};
  const exportSession=async sessionId=>{if(lock.current)return;lock.current=true;setBusy(true);try{const response=await fetch("/api/sessions/export",{method:"POST",headers:{"Content-Type":"application/json","X-Session-Token":window.__SESSION_TOKEN__||""},body:JSON.stringify({sessionId,includePcm:true})});if(!response.ok){const value=await response.json();throw new Error(value.message||"세션을 내보내지 못했습니다.");}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="basslab-session-"+sessionId+".zip";document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}catch(error){onError(error.message);}finally{lock.current=false;if(live.current)setBusy(false);}};
  useEffect(()=>{live.current=true;Promise.all([refresh(),get("sessions/scripts").then(value=>{if(live.current){setScripts(value.scripts||[]);setScriptErrors(value.errors||[]);}})]).catch(error=>onError(error.message));return()=>{live.current=false;};},[]);
  return {snapshot,scripts,scriptErrors,ready,busy,hidden,setHidden,summaryId,setSummaryId,recordPending,setRecordPending,latest,activeRef,accept,acceptSession,refresh,recoverPending,action,exportSession};
}
