// Participant labels are user data on the bridge; no browser storage is used.
function v24Participant(value){const label=value?.participant??value?.participantLabel;return typeof label==="string"&&label.trim()?label.trim():"나";}
function v24ParticipantResults(results,participant,all=false){return all?(results||[]):(results||[]).filter(result=>v24Participant(result)===participant);}
function v24ProfileResultLabel(result){return v24Participant(result)+" · "+v22ResultLabel(result);}
function v24ProfileTakeGate(snapshot,takeId,participant){const gate=v23TakeGate(snapshot,takeId);return gate?.session&&v24Participant(gate.session)!==participant?{...gate,participantRequired:v24Participant(gate.session)}:gate;}
function v24AliasValid(value){const label=String(value||"").normalize("NFC").trim();return !!label&&!/[\u0000-\u001f\u007f]/.test(label)&&new TextEncoder().encode(label).length<=120;}
function useV24Participants(onError){
  const [snapshot,setSnapshot]=useState({participants:[],selected:"나"}),[ready,setReady]=useState(false),[busy,setBusy]=useState(false);
  const latest=useRef(snapshot),live=useRef(true),lock=useRef(false),requests=useRef(new Map());latest.current=snapshot;
  const accept=value=>{const next=value?.participantProfiles||value;if(!next||!Array.isArray(next.participants)||typeof next.selected!=="string")return;if(v2Finite(next.revision)&&v2Finite(latest.current.revision)&&next.revision<latest.current.revision)return;latest.current=next;if(live.current){setSnapshot(next);setReady(true);}};
  const refresh=async()=>{const response=await fetch("/api/participants",{cache:"no-store",headers:{"X-Session-Token":window.__SESSION_TOKEN__||""}}),value=await response.json();v19ReloadForStaleToken(response,value);if(!response.ok)throw new Error(value.message||"지금 치는 사람을 확인하지 못했습니다. 다시 확인해 주세요.");accept(value);return value;};
  const action=async(type,participant)=>{if(lock.current)return false;lock.current=true;setBusy(true);const key=type+":"+participant,requestId=requests.current.get(key)||crypto.randomUUID();requests.current.set(key,requestId);try{const response=await fetch("/api/participants/"+type,{method:"POST",headers:{"Content-Type":"application/json","X-Session-Token":window.__SESSION_TOKEN__||""},body:JSON.stringify({requestId,participant})}),value=await response.json();v19ReloadForStaleToken(response,value);if(!response.ok){requests.current.delete(key);throw new Error(value.message||"이름표를 저장하지 못했습니다.");}accept(value);requests.current.delete(key);return true;}catch(error){onError(error.message);return false;}finally{lock.current=false;if(live.current)setBusy(false);}};
  const exportProfile=async()=>{if(lock.current||!ready)return;lock.current=true;setBusy(true);const participant=latest.current.selected;try{const response=await fetch("/api/participants/export",{method:"POST",headers:{"Content-Type":"application/json","X-Session-Token":window.__SESSION_TOKEN__||""},body:JSON.stringify({participant,includePcm:true})});if(!response.ok){const value=await response.json();throw new Error(value.message||"이 사람의 자료를 내보내지 못했습니다.");}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="basslab-profile-"+new Date().toISOString().replace(/[:.]/g,"-")+".zip";document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}catch(error){onError(error.message);}finally{lock.current=false;if(live.current)setBusy(false);}};
  useEffect(()=>{live.current=true;refresh().catch(error=>onError(error.message));return()=>{live.current=false;};},[]);
  return {snapshot,latest,ready,busy,accept,refresh,action,exportProfile};
}
