function DeviceSettings({participant="나",profileBusy=false,onExportProfile,settings,initialDevices,onDevices,state,results,onSettings,onCommand,onRequest,onError,openCalibration=false}){
  const [devices,setDevices]=useState(initialDevices||{render:[],capture:[]}),[renderId,setRenderId]=useState(settings?.selection?.renderId||""),[captureId,setCaptureId]=useState(settings?.selection?.captureId||""),[channel,setChannel]=useState(settings?.selection?.inputChannel||1),[pending,setPending]=useState(false),[loaded,setLoaded]=useState(!!initialDevices),[saved,setSaved]=useState(false),[guide,setGuide]=useState(openCalibration),[ready,setReady]=useState(false),[exportOpen,setExportOpen]=useState(false),[include,setInclude]=useState([]),[exported,setExported]=useState(false);
  const alive=useRef(false),lock=useRef(false),busy=v13Busy(state),deviceBusy=busy||state.deviceReleased!==true,setupBusy=deviceBusy||v20SessionTerminal(state),selection=settings?.selection,calibration=state.calibrationResult||settings?.calibration,words=v13CalibrationWords(calibration),k=settings?.kFrames??8842,chosenPresent=devices.render.some(d=>d.id===renderId)&&devices.capture.some(d=>d.id===captureId);
  const refresh=async()=>{if(lock.current||deviceBusy)return;lock.current=true;setPending(true);try{const value=await onRequest("devices");if(!alive.current)return;setDevices(value);onDevices?.(value);setLoaded(true);if(value.settings)onSettings(value.settings);else if(typeof value.selectionValid==="boolean")onSettings({...settings,selectionValid:value.selectionValid});}catch(e){onError(v13Error(e.message));}finally{lock.current=false;if(alive.current)setPending(false);}};
  useEffect(()=>{if(openCalibration){setGuide(true);document.getElementById("latency-calibration")?.scrollIntoView({block:"start"});}},[openCalibration]);
  useEffect(()=>{alive.current=true;if(!initialDevices)refresh();return()=>{alive.current=false;};},[]);
  const save=async()=>{if(lock.current||setupBusy)return;lock.current=true;setPending(true);setSaved(false);try{const value=await onRequest("settings",{renderId,captureId,inputChannel:Number(channel)});if(alive.current){onSettings(value.settings||value);setSaved(true);setReady(false);}}catch(e){onError(v13Error(e.message));}finally{lock.current=false;if(alive.current)setPending(false);}};
  const calibrate=async()=>{if(lock.current||setupBusy||!ready||!v13DeviceReady(settings))return;lock.current=true;setPending(true);setReady(false);try{await onCommand("calibrate",{setupConfirmed:true});}catch(e){onError(v13Error(e.message));}finally{lock.current=false;if(alive.current)setPending(false);}};
  const exportZip=async()=>{if(lock.current||busy)return;lock.current=true;setPending(true);setExported(false);try{const response=await fetch("/api/diagnostics",{method:"POST",headers:{"Content-Type":"application/json","X-Session-Token":window.__SESSION_TOKEN__||""},body:JSON.stringify({includePcmTakeIds:include})});if(!response.ok){const value=await response.json();throw new Error(value.message||value.error||"기록을 내보내지 못했습니다.");}const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="basslab-diagnostics-"+new Date().toISOString().replace(/[:.]/g,"-")+".zip";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);if(alive.current)setExported(true);}catch(e){onError(v13Error(e.message));}finally{lock.current=false;if(alive.current)setPending(false);}};
  return <section className="device-settings" aria-label="장치와 지연 설정"><div className="setup-heading"><p className="eyebrow">이 컴퓨터에서 시작하기</p><h2>입력과 출력을 먼저 골라 주세요</h2><p className="muted">장치 이름을 읽는 동안에는 녹음하거나 소리를 내지 않습니다. 설정은 이 폴더에 저장합니다.</p></div>
    <section className="result-card"><p className="card-number">1 · 오디오 장치</p>{!v13DeviceReady(settings)&&<p className="notice">처음 쓰거나 이전 장치가 없습니다. 아래 세 가지를 골라 저장하세요.</p>}<div className="device-selectors"><label>입력 장치<select aria-label="입력 장치" value={captureId} disabled={pending||setupBusy} onChange={e=>{setCaptureId(e.target.value);setSaved(false);}}><option value="">입력을 골라 주세요</option>{devices.capture.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>입력 채널<select aria-label="입력 채널" value={channel} disabled={pending||setupBusy} onChange={e=>{setChannel(Number(e.target.value));setSaved(false);}}><option value={1}>입력 1</option><option value={2}>입력 2</option></select></label><label>출력 장치<select aria-label="출력 장치" value={renderId} disabled={pending||setupBusy} onChange={e=>{setRenderId(e.target.value);setSaved(false);}}><option value="">출력을 골라 주세요</option>{devices.render.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><p className="muted">입력 · 출력 모두 같은 인터페이스를 고르세요.</p><p className="notice click-output-guide"><strong>녹음 중 클릭 출력</strong><br/>클릭 소리는 오디오 인터페이스 출력(헤드폰 · 인터페이스에 붙인 스피커)으로만 나옵니다. 노트북 스피커로는 나오지 않습니다.<br/><small>‘클릭 들으며 미리보기’는 브라우저의 기본 출력 장치를 사용합니다.</small></p><p className="muted">44.1 kHz · 24비트 · 독점 모드로 연결합니다. 같은 인터페이스를 쓰는 다른 앱은 닫아 주세요.</p>{loaded&&(!devices.capture.length||!devices.render.length)&&<p className="notice">장치 목록이 비어 있습니다. 인터페이스를 연결한 뒤 목록을 다시 읽어 주세요.</p>}<div className="actions"><button disabled={pending||deviceBusy} onClick={refresh}>장치 목록 다시 읽기</button><button className="primary" disabled={pending||setupBusy||!chosenPresent} onClick={save}>이 장치로 저장</button></div>{v13DeviceReady(settings)&&!saved&&<p className="saved-message">저장된 장치를 확인했습니다. 다시 저장하지 않고 사용할 수 있습니다.</p>}{saved&&<p className="saved-message" role="status">장치 설정을 저장했습니다. 녹음은 아직 시작하지 않았습니다.</p>}</section>
    <section className="result-card" id="latency-calibration"><p className="card-number">2 · 클릭 지연 확인</p><p>클릭이 출력되어 입력으로 돌아오는 시간을 재서, 연주와 클릭의 앞뒤 위치를 맞추기 위한 측정입니다.</p><h3>{v21CurrentCalibrationValid(settings)?"이 장치에서 잰 값을 사용합니다":"아직 이 장치에서 재지 않았습니다"}</h3><p className="muted">현재 적용 값 {(k/44.1).toFixed(2)} ms {v21CurrentCalibrationValid(settings)?"· 저장된 측정값":"· 기본값"}. 지연 측정은 연습 녹음 목록에 넣지 않습니다.</p>{v21CurrentCalibrationValid(settings)&&<p className="muted">{v21CalibrationDate(settings.calibration)}</p>}<p className="muted">드라이버나 버퍼 설정을 바꾸면 다시 재 주세요.</p><div className="actions"><button disabled={setupBusy||pending||!v13DeviceReady(settings)} onClick={()=>{setGuide(!guide);setReady(false);}}>{guide?"연결 안내 접기":"케이블로 지연 재기"}</button></div>
      {guide&&<div className="calibration-guide"><h3>먼저 케이블을 연결하세요</h3><ol><li>헤드폰 출력의 왼쪽(L)을 <strong>선택한 입력 {selection?.inputChannel||channel}</strong>에 연결합니다. TRS → TS 케이블을 씁니다.</li><li>이 입력은 <strong>LINE</strong>으로, 직접 모니터와 48V는 <strong>끔</strong>으로 둡니다.</li><li>다른 오디오 앱을 닫습니다. 아래 준비 완료를 누를 때만 16클릭을 내고 입력을 읽습니다.</li></ol><label className="check-row"><input type="checkbox" checked={ready} disabled={setupBusy||pending} onChange={e=>setReady(e.target.checked)}/>위 연결과 설정을 마쳤습니다</label><button className="primary" disabled={!ready||setupBusy||pending} onClick={calibrate}>준비 완료 · 16클릭 재기</button></div>}
      {v13Calibrating(state)&&<div className="analysis-banner" role="status"><strong>{state.phase==="CALIBRATION_ANALYZING"?"16클릭의 도착 위치를 확인 중입니다":"지연 측정 중 · 케이블을 그대로 두세요"}</strong><p>완료될 때까지 기다려 주세요. 연습 녹음은 시작하지 않습니다.</p><button disabled={pending||v20SessionTerminal(state)} onClick={()=>onCommand("stop").catch(e=>onError(v13Error(e.message)))}>측정 중단</button></div>}
      {words&&<div className={words.accepted?"calibration-result":"notice"} role="status"><h3>{words.title}</h3><p>{words.detail}</p>{words.accepted&&<p>측정 케이블을 빼고 베이스를 다시 연결하세요. 평소 연주할 입력과 INST 설정으로 돌아간 뒤 연습합니다.</p>}</div>}
    </section>
    <section className="result-card"><p className="card-number">3 · 문제가 생겼을 때</p><h3>기록을 한 파일로 내보내기</h3><p>설정, 최근 실행과 오류, 녹음 설명, ‘이 결과 이상함’ 표시를 ZIP에 담습니다. 녹음 소리는 기본으로 넣지 않습니다.</p><button disabled={busy||pending} onClick={()=>setExportOpen(!exportOpen)}>{exportOpen?"내보내기 선택 접기":"기록 내보내기"}</button><button className="profile-export" disabled={busy||pending||profileBusy||!onExportProfile} onClick={onExportProfile}>이 사람의 자료 내보내기</button><p className="muted profile-export-scope">{participant}의 녹음 소리와 결과, 세션을 담습니다. 장치 선택과 지연값은 모든 이름표가 함께 씁니다.</p>{exportOpen&&<div className="export-options"><p className="muted">소리를 함께 보내려면 정확한 녹음을 직접 선택하세요.</p>{results.length?results.map(r=><label className="check-row" key={r.takeId}><input type="checkbox" checked={include.includes(r.takeId)} disabled={pending} onChange={e=>setInclude(e.target.checked?[...include,r.takeId]:include.filter(id=>id!==r.takeId))}/><span>{r.label||r.taskId} · {v12RecordedLabel(r)}<small>{r.takeId}</small></span></label>):<p className="muted">저장된 녹음이 없습니다. 설정과 실행 기록만 내보냅니다.</p>}<p className="scope">녹음 소리 포함: {include.length}개. 선택하지 않은 녹음은 넣지 않습니다.</p><button className="primary" disabled={pending||busy} onClick={exportZip}>선택한 내용으로 ZIP 다운로드</button>{exported&&<p className="saved-message" role="status">내보내기 파일을 준비했습니다. 브라우저의 다운로드 목록을 확인하세요.</p>}</div>}</section>
  </section>;
}
