function PracticeFlow({state,tasks,onCommand,onError,receivedAt,registerShutdownCleanup,initialConfig=null,settings,onCalibration,participant="나"}){
  const [initial]=useState(()=>v25PracticeInitial(tasks,participant,initialConfig)),groups=v25TaskGroups(tasks,participant);
  const [bpm,setBpm]=useState(initial.bpm),[taskId,setTaskId]=useState(initial.taskId),[route,setRoute]=useState(initial.monitorRoute),[clickMode,setClickMode]=useState(initial.clickMode),[secondaryOpen,setSecondaryOpen]=useState(initial.secondary),[preview,setPreview]=useState(v2Idle()),[frame,setFrame]=useState(v2Idle()),[pending,setPending]=useState(false),[retry,setRetry]=useState(false),[inputNotice,setInputNotice]=useState(false);
  Object.assign(V2_SESSION_CHOICES,{participant,initialConfig,bpm,taskId,monitorRoute:route,clickMode});
  const localAttempts=useRef(new Set()),run=useRef(null),stage=useRef(null),dots=useRef(null),mounted=useRef(false),closing=useRef(Promise.resolve()),busy=useRef(false),postGeneration=useRef(0),anchor=useRef({state,receivedAt,taskId:null}),inputWatch=useRef(null);
  const active=v2Active(state),task=tasks.find(t=>t.taskId===(active?state.selectedTaskId:taskId))||tasks.find(t=>t.taskId===taskId)||tasks[0],noteCount=v24TaskNoteCount(task),previewing=["play","countin"].includes(preview.phase),used=!!task&&(localAttempts.current.has(task.taskId)||(state.attemptBlockedForTaskIds||state.attemptedTaskIds||[]).includes(task.taskId));
  const selectedBpm=active?state.selectedBpm:bpm,firstNote=state.firstNote?.taskId===task?.taskId?state.firstNote:null,matching=firstNote&&task&&Number.isFinite(task.firstMidi)&&Number.isFinite(firstNote.midi)?Math.round(firstNote.midi)===task.firstMidi:null;
  const terminal=v20SessionTerminal(state),disabled=terminal||active||pending||state.deviceReleased!==true||state.phase==="FIRST_NOTE"||state.phase==="ANALYZING"||v13Calibrating(state);
  anchor.current={state,receivedAt,taskId:task?.taskId};
  const closePreview=()=>{
    const current=run.current;run.current=null;setPreview(v2Idle());if(!current)return closing.current;current.disposed=true;cancelAnimationFrame(current.raf);
    for(const node of current.nodes){try{node.osc.stop();node.osc.disconnect();node.gain.disconnect();}catch(error){}}
    const prior=closing.current;closing.current=Promise.all([prior,current.audio?current.audio.close():Promise.resolve()]).then(()=>{});return closing.current;
  };
  useEffect(()=>registerShutdownCleanup?.(()=>{postGeneration.current++;return closePreview();}),[]);
  useEffect(()=>{mounted.current=true;let raf,stopped=false;
    let previous="",lastNotice=false;const tick=now=>{const a=anchor.current;inputWatch.current=v21FirstNoteInput(inputWatch.current,a.state,a.taskId,a.state.serverNowMs+now-a.receivedAt);const notice=inputWatch.current?.noInput===true;if(notice!==lastNotice){lastNotice=notice;setInputNotice(notice);}const next=v2Active(a.state)?v2NativeFrame(a.state,a.receivedAt,now):v2NativeFrame(a.state,now,now),key=JSON.stringify(next);if(key!==previous){setFrame(next);previous=key;}raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);
    const hide=()=>{if(document.hidden){postGeneration.current++;closePreview().catch(()=>{});if(!v20SessionTerminal(anchor.current.state)&&(v2Active(anchor.current.state)||anchor.current.state.phase==="FIRST_NOTE")&&!stopped){stopped=true;onCommand(anchor.current.state.phase==="FIRST_NOTE"?"first-note-stop":"stop",{},true).catch(error=>onError(v13Error(error.message)));}}else stopped=false;};
    const leave=()=>{postGeneration.current++;closePreview().catch(()=>{});if(!v20SessionTerminal(anchor.current.state)&&(v2Active(anchor.current.state)||anchor.current.state.phase==="FIRST_NOTE"))onCommand(anchor.current.state.phase==="FIRST_NOTE"?"first-note-stop":"stop",{},true).catch(()=>{});};
    document.addEventListener("visibilitychange",hide);window.addEventListener("pagehide",leave);
    return()=>{mounted.current=false;cancelAnimationFrame(raf);postGeneration.current++;closePreview().catch(()=>{});document.removeEventListener("visibilitychange",hide);window.removeEventListener("pagehide",leave);};
  },[]);
  const startPreview=async()=>{
    if(disabled||run.current)return;const current={audio:null,nodes:[],disposed:false,raf:null};run.current=current;
    try{await closing.current;if(current.disposed)return;const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw new Error("미리보기 소리를 열지 못했습니다.");current.audio=new Audio();await current.audio.resume();if(current.disposed)return;
      const start=current.audio.currentTime+.08;v2Clicks(bpm,clickMode,noteCount).forEach(click=>{const osc=current.audio.createOscillator(),gain=current.audio.createGain(),when=start+click.offsetMs/1000;osc.frequency.setValueAtTime(click.frequency,when);gain.gain.setValueAtTime(0,when);gain.gain.linearRampToValueAtTime(.045,when+.003);gain.gain.exponentialRampToValueAtTime(.0001,when+click.duration);osc.connect(gain);gain.connect(current.audio.destination);current.nodes.push({osc,gain});osc.start(when);osc.stop(when+click.duration+.01);});
      let scrolled=false;const tick=now=>{if(current.disposed)return;if(!scrolled){stage.current?.scrollIntoView({block:"start"});scrolled=true;}const stamp=current.audio.getOutputTimestamp?.(),clock=stamp?.contextTime>0&&stamp?.performanceTime>0?stamp.contextTime+(now-stamp.performanceTime)/1000:current.audio.currentTime;const f=v2Frame(bpm,Math.max(0,clock-start),0,noteCount);setPreview(f);if(f.phase==="stop"&&clock-start>=(8+noteCount/4)*60/bpm+.20){closePreview().catch(()=>{});setPreview(f);return;}current.raf=requestAnimationFrame(tick);};current.raf=requestAnimationFrame(tick);
    }catch(error){closePreview().catch(()=>{});onError(v13Error(error.message));}
  };
  const issue=async(type,fields={})=>{
    if(busy.current)return;if(v20SessionTerminal(anchor.current.state)){onError(v20SessionMessage(anchor.current.state));return false;}busy.current=true;setPending(true);const generation=++postGeneration.current;
    try{await closePreview();if((type==="record"||type==="first-note")&&(!mounted.current||document.hidden||generation!==postGeneration.current))return;
      if(type==="record")localAttempts.current.add(task.taskId);await onCommand(type,{taskId:task?.taskId,bpm,monitorRoute:route,clickMode,...fields});if(type==="record")setRetry(false);if(type==="retry")localAttempts.current.delete(task.taskId);return true;
    }catch(error){onError(v13Error(error.message));return false;}finally{busy.current=false;if(mounted.current)setPending(false);}
  };
  const shown=active?frame:state.phase==="ANALYZING"?{phase:"analyzing"}:(["SAVED","ENDED"].includes(state.phase)&&state.lastSavedTakeId&&!previewing?{phase:"saved"}:preview),slot=task?.slots?.[(shown.noteIndex||1)-1]||{string:task?.string||"A",fret:0},firstChecked=!!firstNote&&firstNote.taskId===task?.taskId;
  useEffect(()=>{if(noteCount<=32||!shown.noteIndex)return;const container=dots.current,target=container?.querySelector(".current");if(!target)return;const box=container.getBoundingClientRect(),item=target.getBoundingClientRect();if(item.top<box.top||item.bottom>box.bottom)container.scrollTop+=item.top-box.top-container.clientHeight/2+item.height/2;},[shown.noteIndex,noteCount]);
  const startAllowed=state.captureEnabled===true&&!disabled&&!!task&&firstChecked;
  const chooseTask=id=>{closePreview().catch(()=>{});const next=v25TeacherTaskSelection(tasks.find(item=>item.taskId===id),{bpm,clickMode});setTaskId(next.taskId);setBpm(next.bpm);setClickMode(next.clickMode);};
  return <section className="practice" aria-label="한 과제 연습">
    {!v21CurrentCalibrationValid(settings)&&<div className="notice calibration-warning" role="status"><strong>{V21_UNCALIBRATED_WARNING}</strong><button disabled={v13Busy(state)} onClick={onCalibration}>지연 재기</button></div>}
    <div className="notice">{terminal?v20SessionMessage(state):initialConfig?"선택한 녹음의 과제와 빠르기, 클릭, 모니터 경로를 가져왔습니다. 첫 음 확인이 필요하면 확인한 뒤 직접 녹음을 시작하세요. 앞 녹음은 그대로 남습니다.":"준비가 되면 직접 녹음을 시작하세요. 다시 녹음해도 앞 녹음은 그대로 남습니다."}</div>
    <div className="practice-settings"><label>한 번에 과제 하나<select value={groups.primary.some(item=>item.taskId===task?.taskId)?task.taskId:""} disabled={disabled} onChange={event=>chooseTask(event.target.value)}>{!groups.primary.some(item=>item.taskId===task?.taskId)&&<option value="" disabled>아래 목록에서 과제 선택됨</option>}{groups.primary.map(item=><option key={item.taskId} value={item.taskId}>{item.label}</option>)}</select></label><label>빠르기<select value={bpm} disabled={disabled} onChange={event=>{closePreview().catch(()=>{});setBpm(Number(event.target.value));}}>{V2_BPMS.map(value=><option key={value} value={value}>{value} BPM</option>)}</select></label><label>클릭<select value={clickMode} disabled={disabled} onChange={event=>{closePreview().catch(()=>{});setClickMode(event.target.value);}}>{Object.entries(V2_CLICK_MODES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>내 소리를 듣는 길<select value={route} disabled={disabled} onChange={event=>setRoute(event.target.value)}>{Object.entries(V2_ROUTES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>
    <details className="task-secondary" open={secondaryOpen} onToggle={event=>setSecondaryOpen(event.currentTarget.open)}><summary>{groups.secondaryLabel}</summary><label>{groups.secondaryLabel}에서 선택<select aria-label={groups.secondaryLabel+"에서 선택"} value={groups.secondary.some(item=>item.taskId===task?.taskId)?task.taskId:""} disabled={disabled} onChange={event=>chooseTask(event.target.value)}><option value="" disabled>과제를 고르세요</option>{groups.secondary.map(item=><option key={item.taskId} value={item.taskId}>{item.label}</option>)}</select></label></details>
    <p className="selected-task-label">{task?.label}</p>
    <p className="muted">기본 60 · 상한 80 BPM. {task?.group==="teacher"?"새 음을 칠 때 앞 음이 자연스럽게 뮤트되어도 됩니다.":task?.instruction||"새 음을 칠 때 앞 음이 자연스럽게 뮤트되어도 됩니다."} {noteCount===32?"두 마디":Math.ceil(noteCount/16)+"마디"} {noteCount}음입니다.</p>
    <div className="actions"><button disabled={disabled||previewing} onClick={startPreview}>클릭 들으며 미리보기</button><button disabled={!previewing} onClick={()=>closePreview().catch(error=>onError(v13Error(error.message)))}>미리보기 멈추기</button></div>
    {task?.group==="teacher"&&<p className="teacher-instruction" role="note">{task.instruction}</p>}
    <section className={"practice-stage stage-"+shown.phase} ref={stage} data-phase={shown.phase} aria-label="큰 연주 안내"><div className="stage-top"><span>{active?"녹음 안내":previewing?"미리보기 · 녹음 안 함":"준비된 안내"}</span><span>{selectedBpm} BPM · {noteCount}음</span></div>
      {shown.phase==="analyzing"?<div className="stage-main"><div><span className="stage-signal">저장 완료</span><h2>분석 중 · 잠시 기다려 주세요</h2><p>끝나면 방금 녹음한 결과가 자동으로 열립니다.</p></div></div>:shown.phase==="countin"?<><div className="stage-main"><div><span className="stage-signal">WAIT</span><h2>아직 치지 마세요</h2><p>준비 8박 뒤 GO에서 시작</p></div><strong className="stage-count">{shown.remaining}</strong></div></>:
       shown.phase==="play"?<div className="stage-main"><div><span className="stage-signal">{shown.noteIndex>=noteCount-3?"마지막 4음":"GO · 지금 연주"}</span>{shown.noteIndex>=noteCount-3&&<strong className="last-four">{noteCount+1-shown.noteIndex}음 뒤 STOP</strong>}<h2>{slot.noteName||""}{slot.noteName?" · ":""}{slot.string||""}현 {slot.fret===0?"개방현":slot.fret+"프렛"}</h2><p>{clickMode==="quarter"?"한 박에 네 음":"클릭마다 한 음"} · 지금은 연주만</p></div><strong className="stage-count">{shown.noteIndex}<small>/{noteCount}</small></strong></div>:
       shown.phase==="stop"||shown.phase==="saved"||shown.phase==="saving"?<div className="stage-main"><div><span className="stage-signal">STOP</span><h2>{shown.phase==="saved"?"결과 준비됨":"끝 소리 · 모든 줄을 막으세요"}</h2><p>{active?"저장 중입니다. 잠시 기다려 주세요.":shown.phase==="saved"?"이제 더 치지 마세요. 녹음을 마쳤습니다.":"미리보기 끝 · 녹음하지 않았습니다."}</p></div><strong className="stage-count">■</strong></div>:
       shown.phase==="waiting"||shown.phase==="preparing"?<div className="stage-main"><div><span className="stage-signal">WAIT</span><h2>시작 시점 확인 중</h2><p>아직 치지 마세요. 시간을 확인한 뒤 안내합니다.</p></div></div>:
       <div className="stage-main"><div><span className="stage-signal">8 → 1 → GO</span><h2>준비는 여덟 박, 연주는 {noteCount===32?"두 마디":Math.ceil(noteCount/16)+"마디"}</h2><p>GO에서 첫 음 · 끝 소리와 STOP에서 줄 막기</p></div></div>}
      <div ref={dots} className={"position-dots"+(noteCount>32?" long-take-dots":"")} aria-label={noteCount+"음 순서"}>{Array.from({length:noteCount},(_,index)=><span key={index} className={shown.noteIndex===index+1?"current":shown.noteIndex>index+1?"past":""}>{index+1}</span>)}</div>
    </section>
    <div className="practice-bottom"><section className="result-card"><p className="card-number">첫 음 확인</p><h3>과제의 첫 음 · {task?.firstNoteName||"A1"}</h3><p>첫 음 확인 버튼을 누른 뒤 해당 음을 한 번 튕겨 보세요. 음 이름과 입력 소리 레벨만 확인합니다.</p>{firstNote?<div className={matching===false?"first-note mismatch":"first-note"}><strong>{matching===false?"과제는 "+task?.firstNoteName+" · 들린 음은 ":"들린 음 · "}{firstNote.noteName||"아직 읽지 못함"}</strong><div className="input-meter" role="meter" aria-label="입력 소리 레벨" aria-valuemin={-84} aria-valuemax={0} aria-valuenow={v2Finite(firstNote.levelDbfs)?firstNote.levelDbfs:-84}><span style={{width:(v2Finite(firstNote.levelDbfs)?Math.max(0,Math.min(100,(firstNote.levelDbfs+84)/84*100)):0)+"%"}}/></div>{matching===false&&<p>과제와 다르게 들렸습니다. 확인하고 계속할 수 있습니다. 녹음을 막지는 않습니다.</p>}</div>:<p className="muted">{state.firstNote?"이 과제의 첫 음을 확인해 주세요":"아직 장치를 열지 않았습니다."}</p>}
      {inputNotice&&<p className="notice first-note-input-warning" role="status">{V21_INPUT_WARNING}</p>}<div className="actions"><button disabled={!state.captureEnabled||disabled} onClick={()=>issue("first-note")}>첫 음 확인하기</button>{state.phase==="FIRST_NOTE"&&<button disabled={pending||terminal} onClick={()=>issue("first-note-stop")}>확인 마치기</button>}</div></section>
      <section className="result-card"><p className="card-number">녹음과 보존</p><h3>{active?"연주 중에는 분석 표시가 없습니다":used?"저장된 녹음이 있습니다":"준비되면 직접 시작"}</h3>{!state.captureEnabled&&<p className="notice">장치 설정을 먼저 확인해 주세요. 준비되지 않은 장치는 녹음을 시작하지 않습니다.</p>}
      <div className="actions"><button className="primary" disabled={!startAllowed} onClick={()=>issue("record")}>{used?"이 설정으로 다시 녹음":"이 설정으로 녹음 시작"}</button>{active&&<button className="stop" disabled={pending||terminal} onClick={()=>issue("stop")}>중단하고 보존</button>}</div><p className="muted">버튼을 누를 때마다 새 녹음으로 저장합니다. 자동으로 반복하지 않습니다.</p><p className="scope">{state.deviceReleased===true?"장치 해제됨":"장치 해제 상태를 확인 중"}</p><button disabled={pending||terminal||state.deviceReleased===true} onClick={()=>issue("end")}>이번 연습 마치기 · 결과 화면 유지</button><p className="muted">이 버튼으로 연습 세션을 마치면 새 녹음을 할 수 없습니다. 다시 녹음하려면 프로그램 종료를 완료한 뒤 BassLab.exe를 다시 실행하세요.</p></section></div>
  </section>;
}
