function GuidedSessionPicker({guided,participant="나",onStart,onResume,onEnd}){
  const [scriptId,setScriptId]=useState("teacher-2026-10-07");
  const selected=guided.scripts.find(script=>script.id===scriptId)||guided.scripts[0],history=guided.snapshot.sessions.filter(session=>v24Participant(session)===participant),summary=history.find(session=>session.sessionId===guided.summaryId),active=guided.snapshot.active,other=active&&v24Participant(active)!==participant;
  return <section className="guided-panel" aria-label="검수 세션"><h2>검수 세션 · {participant}</h2>{summary?<GuidedSessionSummary session={summary} busy={guided.busy} onExport={()=>guided.exportSession(summary.sessionId)} onClose={()=>guided.setSummaryId(null)}/>:<>{active?<div className="result-card"><h3>{other?v24Participant(active)+"의 진행 중인 세션이 있습니다":"이어 할 세션 · "+active.scriptSnapshot.title}</h3><p>{v24Participant(active)} · {v23StepLabel(active)}{other&&" · 이 세션을 잇거나 끝낸 뒤 새 세션을 시작할 수 있습니다."}</p><button disabled={guided.busy} onClick={()=>onResume(active)}>{other?"이름표 바꾸고 이어서 하기":"이어서 하기"}</button>{other&&<button disabled={guided.busy} onClick={()=>onEnd?.(active)}>기존 세션 끝내기</button>}</div>:<div className="result-card"><label>과제 묶음<select aria-label="과제 묶음" value={selected?.id||""} onChange={event=>setScriptId(event.target.value)}>{guided.scripts.map(script=><option key={script.id} value={script.id}>{script.title}</option>)}</select></label><p className="session-participant">참가자 이름표 · <strong>{participant}</strong></p><p className="muted">위의 ‘지금 치는 사람’을 그대로 사용합니다. 실명 대신 별명을 써 주세요.</p><button className="primary" disabled={guided.busy||!selected} onClick={()=>onStart(selected.id)}>세션 시작</button></div>}{guided.scriptErrors.length>0&&<p className="notice">읽지 못한 과제 묶음 {guided.scriptErrors.length}개가 있습니다. 파일 형식을 확인해 주세요. 다른 묶음과 일반 연습은 사용할 수 있습니다.</p>}<section className="result-card"><h3>{participant}의 남겨 둔 세션</h3>{history.length?history.map(session=><button className="session-history-row" key={session.sessionId} onClick={()=>guided.setSummaryId(session.sessionId)}>{session.scriptSnapshot?.title||session.scriptId} · {v24Participant(session)} · {session.endedAt?"끝냄":"진행 중"} · {v22RecordedLabel({recordedAt:session.startedAt})}</button>):<p className="muted">아직 세션 기록이 없습니다.</p>}</section></>}</section>;
}

function GuidedSessionBanner({session,busy,engineBusy,onOpen,onNext,onSkip,onEnd,onHide}){const definition=v23StepDefinition(session),step=v23StepState(session);if(!definition)return null;return <section className="guided-banner" aria-label="진행 중인 검수 세션"><div><strong>{v24Participant(session)} · {v23StepLabel(session)} · {definition.type==="record"?v22ResultLabel({...definition,tempo:{metronomeBpm:definition.bpm},recordedAt:null}).split(" · 날짜 기록 없음")[0]:session.scriptSnapshot.title}</strong><p>{definition.instruction||definition.question||(definition.type==="questions"?"질문에 짧게 답해 주세요.":"")}{definition.optional&&" (선택 단계)"}</p>{definition.expected&&step?.takes?.some(take=>take.viewedAt)&&<details className="session-expected"><summary>녹음 뒤 확인할 내용</summary><p>{definition.expected}</p></details>}</div><div className="actions"><button disabled={busy||engineBusy} onClick={onOpen}>이 단계 열기</button><button disabled={busy||engineBusy||!v23StepComplete(session)} onClick={onNext}>다음</button><button disabled={busy||engineBusy} onClick={onSkip}>건너뜀</button><button disabled={busy} onClick={onEnd}>세션 끝내기</button><button disabled={busy||engineBusy} onClick={onHide}>일반 연습으로 전환</button></div></section>;}
function GuidedResultGate({gate,busy,onView,onRefresh,onSwitchParticipant}){
  const attempted=useRef(false);useEffect(()=>{if(!busy&&!gate.loading&&!gate.participantRequired&&gate.requiresBefore===false&&!attempted.current){attempted.current=true;onView(gate,null);}},[gate.takeId,gate.loading,gate.requiresBefore,gate.participantRequired,busy]);
  if(gate.participantRequired)return <section className="result-card guided-owner-gate"><h2>{gate.participantRequired}의 그림 보기 전 답이 남아 있습니다</h2><p>이름표를 {gate.participantRequired}(으)로 바꾼 뒤 답하거나, 답 없이 본 기록을 남길 수 있습니다.</p><button disabled={busy||!onSwitchParticipant} onClick={()=>onSwitchParticipant(gate)}>이름표 바꾸고 계속</button></section>;
  return gate.loading?<section className="result-card guided-result-pending"><h2>세션의 녹음 연결을 확인하고 있습니다</h2><p>연결과 답 저장 상태를 확인한 뒤 그림을 엽니다.</p><button disabled={busy} onClick={onRefresh}>세션 상태 다시 확인</button></section>:gate.requiresBefore===false?<section className="result-card guided-result-pending"><p>그림을 연 기록을 저장하고 있습니다.</p><button disabled={busy} onClick={()=>onView(gate,null)}>그림 열기 다시 시도</button></section>:<GuidedBeforeGate gate={gate} busy={busy} onView={onView}/>;
}
function GuidedBeforeGate({gate,busy,onView}){
  const [direction,setDirection]=useState(""),[unstable,setUnstable]=useState([]),[memo,setMemo]=useState("");const questions=gate.definition?.beforeQuestions||[],overall=questions.find(question=>question.id==="overall"),shaken=questions.find(question=>question.id==="shaken"),note=questions.find(question=>question.id==="memo");
  return <section className="guided-before result-card" aria-label="그림 보기 전 답"><p className="eyebrow">녹음 저장 · 그림 보기 전</p><h2>먼저 귀로 느낀 것을 적어 주세요</h2><fieldset><legend>{overall?.question||"전체로 클릭보다 앞 · 뒤 · 같이?"}</legend>{(overall?.options||["앞","뒤","같이"]).map(value=><label key={value}><input type="radio" name={"before-"+gate.takeId} checked={direction===value} disabled={busy} onChange={()=>setDirection(value)}/>{value}</label>)}</fieldset><fieldset><legend>{shaken?.question||"흔들린 곳"}</legend>{(shaken?.options||["처음","가운데","끝","없음"]).map(value=><label key={value}><input type="checkbox" checked={unstable.includes(value)} disabled={busy} onChange={()=>setUnstable(old=>v23ToggleUnstable(old,value,shaken?.exclusiveOption||"없음"))}/>{value}</label>)}</fieldset><label>{note?.question||"메모 한 줄"}<input aria-label="그림 전 메모" value={memo} maxLength={1000} disabled={busy} onChange={event=>setMemo(event.target.value)}/></label><div className="actions"><button className="primary" disabled={busy||!direction||!unstable.length} onClick={()=>onView(gate,{direction,unstable,memo})}>답하고 그림 보기</button><button disabled={busy} onClick={()=>onView(gate,null)}>답 없이 그림 보기</button></div><p className="muted">답을 저장한 뒤 그림을 엽니다. 건너뛰어 열면 ‘답 없이 봄’으로 남습니다.</p></section>;
}
function GuidedListenPanel({session,busy,onPlay,onAnswer}){
  const definition=v23StepDefinition(session),step=v23StepState(session),answers=step?.listenAnswers||[],remaining=definition.slots.find(slot=>!answers.some(answer=>answer.slot===slot)),[chosen,setChosen]=useState(null),[played,setPlayed]=useState(null),slot=chosen??remaining??definition.slots[0];
  return <section className="guided-listen result-card" aria-label="세션 함께 듣기"><h3>함께 듣고 답하기</h3><p>{definition.question}</p><div className="actions">{definition.slots.map(value=><button key={value} aria-pressed={slot===value} onClick={()=>{setChosen(value);setPlayed(null);}}>{value}번{answers.some(answer=>answer.slot===value)?" · 답 저장됨":""}</button>)}</div><button className="primary" disabled={busy} onClick={async()=>{if(await onPlay(slot)!==false)setPlayed(slot);}}>{slot}번 · 0.25배로 구간 반복 듣기</button><div className="actions">{definition.options.map(answer=><button key={answer} disabled={busy||played!==slot||answers.some(item=>item.slot===slot)} onClick={async()=>{if(await onAnswer(slot,answer)){setChosen(null);setPlayed(null);}}}>{answer}</button>)}</div><p className="muted">듣기 버튼을 누를 때만 소리가 납니다. 재생 멈추기로 반복을 끝낼 수 있습니다.</p></section>;
}
function GuidedQuestions({session,busy,onSave}){const definition=v23StepDefinition(session),step=v23StepState(session),[answers,setAnswers]=useState(()=>definition.questions.map((_,index)=>step?.answers?.[index]||"")),budget=v23QuestionsBudget(session,answers);return <section className="guided-questions result-card"><h2>마지막 질문</h2>{definition.questions.map((question,index)=><label key={index}>{index+1}. {question}<textarea aria-label={"질문 "+(index+1)} value={answers[index]} disabled={busy||step?.answers?.length===definition.questions.length} maxLength={2000} onChange={event=>setAnswers(old=>old.map((value,i)=>i===index?event.target.value:value))}/></label>)}<p className={budget.allowed?"muted question-budget":"notice question-budget"} role="status">답 전체 저장 용량 {budget.bytes.toLocaleString()} / {budget.limit.toLocaleString()}바이트 · {budget.allowed?budget.remaining.toLocaleString()+"바이트 남음":(-budget.remaining).toLocaleString()+"바이트 초과 — 답을 조금 줄여 주세요."}</p><button className="primary" disabled={busy||!budget.allowed||step?.answers?.length===definition.questions.length} onClick={()=>{if(budget.allowed)onSave(answers);}}>질문 답 저장</button>{step?.answers?.length===definition.questions.length&&<p className="saved-message">질문 답을 저장했습니다. 다음을 누르면 세션을 마칩니다.</p>}</section>;}
function GuidedSessionSummary({session,busy,onExport,onClose}){return <section className="session-summary result-card"><h3>{session.scriptSnapshot.title} · {session.participantLabel}</h3><p>{session.endedAt?"세션을 마쳤습니다. 녹음과 답은 그대로 남습니다.":"진행 중인 세션의 저장 기록입니다."}</p><ol>{session.steps.map((step,index)=>{const definition=v23StepDefinition(session,index);return <li key={index}><strong>{definition?.id||index+1} · {definition?.instruction||definition?.question||"질문"}</strong>{step.skipped&&<p>건너뜀 · {step.skipReason||"사용자 선택"}</p>}{(step.takes||[]).map(take=><div key={take.takeId}><p>녹음 · {take.takeId}</p><p>{take.beforeAnswers?take.beforeAnswers.direction+" · "+take.beforeAnswers.unstable.join(" · ")+(take.beforeAnswers.memo?" · "+take.beforeAnswers.memo:""):take.viewedAt?"답 없이 봄":"그림 보기 전"}</p></div>)}{(step.listenAnswers||[]).map((answer,i)=><p key={i}>{answer.slot}번 · {answer.answer}</p>)}{(step.answers||[]).map((answer,i)=><p key={i}>{i+1}. {answer||"답 없음"}</p>)}</li>;})}</ol><p className="muted">녹음 소리를 기본으로 포함합니다. 이 파일을 다른 사람에게 자동으로 보내지는 않습니다.</p><div className="actions"><button className="primary" disabled={busy} onClick={onExport}>세션 내보내기</button><button onClick={onClose}>세션 목록</button></div></section>;}
