function ObservationApp(){
  const [view,setView]=useState("results"),[state,setState]=useState({phase:"LOADING",captureEnabled:false,distinctTaskCount:0}),[results,setResults]=useState([]),[tasks,setTasks]=useState([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[receivedAt,setReceivedAt]=useState(0),[selectedTakeId,setSelectedTakeId]=useState(null),[readyTake,setReadyTake]=useState(null),[settings,setSettings]=useState(null),[deviceList,setDeviceList]=useState(null),[practiceSetup,setPracticeSetup]=useState(null),[calibrationGuide,setCalibrationGuide]=useState(false);
  const mounted=useRef(false),lastStamp=useRef(-Infinity),previousState=useRef(null),lastCompletion=useRef(null),resultRequest=useRef(0),pendingTarget=useRef(null),initialSelection=useRef(false),resultBusy=useRef(false),lastResultAttempt=useRef(0),resultAttempts=useRef(0),calibrationStamp=useRef(null);
  const shutdown=useProgramShutdown(state.phase),eventsRef=useRef(null),guided=useV23Sessions(setError),profiles=useV24Participants(setError),[allParticipants,setAllParticipants]=useState(false),resumeAfterProfile=useRef(null),takeAfterProfile=useRef(null),[teacherGuided,setTeacherGuided]=useState(false);
  shutdown.updates.current=closeEvents=>{if(closeEvents){eventsRef.current?.close();eventsRef.current=null;}resultRequest.current++;pendingTarget.current=null;};
  const read=async route=>{if(shutdown.locked.current)throw new Error("프로그램 종료 중에는 새 작업을 시작하지 않습니다.");const response=await fetch("/api/"+route,{headers:{"X-Session-Token":window.__SESSION_TOKEN__||""}}),data=await response.json();v19ReloadForStaleToken(response,data);if(!response.ok)throw new Error(data.message||"화면 정보를 불러오지 못했습니다.");return data;};
  const request=async(route,body)=>{if(shutdown.locked.current)throw new Error("프로그램 종료 중에는 새 작업을 시작하지 않습니다.");const response=await fetch("/api/"+route,{method:body===undefined?"GET":"POST",headers:{"X-Session-Token":window.__SESSION_TOKEN__||"",...(body===undefined?{}:{"Content-Type":"application/json"})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();v19ReloadForStaleToken(response,data);if(!response.ok)throw new Error(data.message||data.error||"요청을 마치지 못했습니다.");if(data.state&&mounted.current)accept(data.state);return data;};
  const refreshResults=async target=>{
    if(shutdown.locked.current)return;
    const request=++resultRequest.current;if(target||pendingTarget.current)resultAttempts.current++;resultBusy.current=true;lastResultAttempt.current=Date.now();let data;try{data=await read("results");}finally{resultBusy.current=false;}
    if(!mounted.current||shutdown.locked.current||request!==resultRequest.current)return;
    await guided.refresh();
    if(!mounted.current||shutdown.locked.current||request!==resultRequest.current)return;
    const next=data.results||[];setResults(next);
    const wanted=target||pendingTarget.current;
    if(wanted&&next.some(r=>r.takeId===wanted)){setSelectedTakeId(wanted);setReadyTake(wanted);setView(current=>current==="settings"?current:"results");pendingTarget.current=null;initialSelection.current=true;}
    else if(!initialSelection.current&&next.length){const latest=next.slice().sort((a,b)=>(Date.parse(b.recordedAt||b.finishedAt||b.createdAt)||0)-(Date.parse(a.recordedAt||a.finishedAt||a.createdAt)||0))[0];setSelectedTakeId(latest.takeId);initialSelection.current=true;}
  };
  const accept=next=>{
    if(next?.guidedSessions)guided.accept(next.guidedSessions);if(next?.participantProfiles)profiles.accept(next.participantProfiles);
    if(next?.shutdown)shutdown.observe(next.shutdown);
    if(shutdown.locked.current)return;
    if(!next||typeof next.phase!=="string")return;
    if(v2Finite(next.serverNowMs)&&next.serverNowMs<lastStamp.current)return;
    if(v2Finite(next.serverNowMs))lastStamp.current=next.serverNowMs;
    const prior=previousState.current,completion=v12CompletionKey(prior,next);previousState.current=next;
    setReceivedAt(performance.now());setState(next);
    if(next.phase==="CALIBRATION_SAVED"){const key=JSON.stringify(next.calibrationResult||next.calibration||{});if(key!==calibrationStamp.current){calibrationStamp.current=key;read("settings").then(value=>{if(mounted.current)setSettings(value);}).catch(error=>setError(v13Error(error.message)));}}
    if(["FIRST_NOTE","STARTING","RECORDING","SAVING","ANALYZING"].includes(next.phase))setReadyTake(null);
    if(completion&&completion!==lastCompletion.current){lastCompletion.current=completion;resultAttempts.current=0;pendingTarget.current=next.lastSavedTakeId;refreshResults(next.lastSavedTakeId).catch(error=>setError(error.message));}else if(completion&&pendingTarget.current&&resultAttempts.current<3&&!resultBusy.current&&Date.now()-lastResultAttempt.current>=2000){refreshResults(pendingTarget.current).catch(error=>setError(error.message));}
  };
  const rawCommand=async(type,fields={},keepalive=false)=>{if(shutdown.locked.current)throw new Error("프로그램 종료 중에는 새 작업을 시작하지 않습니다.");if(v20SessionTerminal(state)&&["first-note","first-note-stop","record","stop","end","retry","calibrate"].includes(type))throw new Error(v20SessionMessage(state));const response=await fetch("/api/command",{method:"POST",keepalive,headers:{"Content-Type":"application/json","X-Session-Token":window.__SESSION_TOKEN__||""},body:JSON.stringify({type,requestId:crypto.randomUUID(),...fields})});const data=await response.json();v19ReloadForStaleToken(response,data);if(!response.ok)throw new Error(data.message||data.error||"요청 결과를 확인하지 못했습니다.");if(data.participantProfiles)profiles.accept(data.participantProfiles);if(data.guidedSessions)guided.accept(data.guidedSessions);else if(data.session)guided.acceptSession(data.session);if(data.state&&mounted.current)accept(data.state);if(["exclude","note"].includes(type))await refreshResults();return data;};
  const command=async(type,fields={},keepalive=false)=>{if(type==="first-note"){if(!profiles.ready)throw new Error("지금 치는 사람을 확인한 뒤 첫 음을 확인해 주세요.");return rawCommand(type,{...fields,participant:profiles.latest.current.selected},keepalive);}if(type!=="record")return rawCommand(type,fields,keepalive);if(!guided.ready||!profiles.ready)throw new Error("세션과 지금 치는 사람을 확인한 뒤 녹음을 시작해 주세요.");fields={...fields,participant:profiles.latest.current.selected};const binding=v23RecordBinding(profiles.latest.current.selected==="선생님"&&!teacherGuided?null:guided.activeRef.current,fields);if(!binding)return rawCommand(type,fields,keepalive);guided.setRecordPending(true);try{return await rawCommand(type,{...fields,...binding},keepalive);}finally{try{await guided.refresh();guided.setRecordPending(false);}catch(error){setError("세션의 녹음 연결을 확인하지 못했습니다. 세션 상태를 다시 확인해 주세요.");}}};
  useEffect(()=>{const pauseOthers=event=>{if(event.target.tagName==="AUDIO"&&shutdown.locked.current){event.target.pause();return;}if(event.target.tagName==="AUDIO")document.querySelectorAll("audio").forEach(audio=>{if(audio!==event.target)audio.pause();});};document.addEventListener("play",pauseOthers,true);return()=>document.removeEventListener("play",pauseOthers,true);},[]);
  useEffect(()=>{mounted.current=true;Promise.all([read("state").then(accept),refreshResults(),read("tasks").then(data=>{if(mounted.current)setTasks(data.tasks||[]);}),read("settings").then(async value=>{if(shutdown.locked.current)return;if(value.selection){const devices=await read("devices");value=devices.settings||{...value,selectionValid:devices.selectionValid===true};if(mounted.current)setDeviceList(devices);}if(mounted.current){setSettings(value);if(!v13DeviceReady(value))setView("settings");}})]).catch(error=>setError(error.message)).finally(()=>{if(mounted.current)setLoading(false);});const connectEvents=()=>{if(!mounted.current||shutdown.locked.current||eventsRef.current)return;try{const events=new EventSource("/api/events");eventsRef.current=events;events.onmessage=event=>{try{if(mounted.current)accept(JSON.parse(event.data));}catch(error){setError("현재 상태를 해석하지 못했습니다.");}};}catch(error){setError("프로그램 연결을 준비하지 못했습니다. 잠시 뒤 다시 열어 주세요.");}};const hide=()=>{eventsRef.current?.close();eventsRef.current=null;};const show=event=>{if(event.persisted)connectEvents();};connectEvents();window.addEventListener("pagehide",hide);window.addEventListener("pageshow",show);return()=>{mounted.current=false;window.removeEventListener("pagehide",hide);window.removeEventListener("pageshow",show);hide();};},[]);
  const engineError=v13Error(state.lastError);
  const terminal=v20SessionTerminal(state),practiceAgainAvailability=result=>v20PracticeAgainAvailability(result,tasks,state,loading,shutdown.locked.current);
  const practiceAgain=result=>{const availability=practiceAgainAvailability(result);if(!availability.allowed){setError(availability.reason);return;}const retry=v20RetryConfig(result,tasks);setPracticeSetup(previous=>({id:(previous?.id||0)+1,config:retry.config}));setReadyTake(null);setError("");setView(v13DeviceReady(settings)?"practice":"settings");};
  const openGuidedStep=async session=>{
    if(!session||session.endedAt)return;const definition=v23StepDefinition(session),step=v23StepState(session);if(!definition)return;
    if(definition.type==="record"){
      const takeId=step?.takeIds?.at(-1);if(takeId){const saved=results.find(result=>result.takeId===takeId);if(saved){setSelectedTakeId(takeId);setView("results");}else{setView("results");setError("이 단계의 녹음을 저장·분석하고 있습니다. 결과가 준비되면 열립니다.");}return;}
      const monitorRoute=Object.hasOwn(V2_ROUTES,V2_SESSION_CHOICES.monitorRoute)?V2_SESSION_CHOICES.monitorRoute:"unknown";
      practiceAgain({taskId:definition.taskId,tempo:{metronomeBpm:definition.bpm},clickMode:definition.clickMode,monitorRoute});
    }else if(definition.type==="listen"){
      if(step?.skipped){await nextGuidedStep(session);return;}
      if(!results.some(result=>result.takeId===definition.takeId)){const skipped=await guided.action("skip",{sessionId:session.sessionId,stepIndex:session.currentStepIndex,reason:"recording-not-found"});if(skipped)await nextGuidedStep(skipped);return;}
      const recording=results.find(result=>result.takeId===definition.takeId);if(v24Participant(recording)!==profiles.latest.current.selected){setAllParticipants(true);setError("함께 듣는 녹음은 "+v24Participant(recording)+"의 자료입니다. 전체 보기로 열었습니다.");}setSelectedTakeId(definition.takeId);setView("results");
    }else setView("questions");
  };
  const startGuidedSession=async scriptId=>{setTeacherGuided(true);const participant=profiles.latest.current.selected;if(!profiles.ready)return;const session=await guided.action("start",{scriptId,participant,participantLabel:participant});if(session)await openGuidedStep(session);};
  const endGuidedSession=async session=>{const ended=await guided.action("end",{sessionId:session.sessionId});if(ended)setView("sessions");};
  const nextGuidedStep=async session=>{if(!v23StepComplete(session))return;const stepIndex=session.currentStepIndex+1;if(stepIndex>=session.scriptSnapshot.steps.length){await endGuidedSession(session);return;}const next=await guided.action("step",{sessionId:session.sessionId,stepIndex});if(next)await openGuidedStep(next);};
  const skipGuidedStep=async session=>{const skipped=await guided.action("skip",{sessionId:session.sessionId,stepIndex:session.currentStepIndex,reason:"사용자 건너뜀"});if(skipped)await nextGuidedStep(skipped);};
  const viewGuidedTake=async(gate,answers)=>{if(gate.session&&v24Participant(gate.session)!==profiles.latest.current.selected){setError("이 녹음의 이름표로 바꾼 뒤 그림 보기 전 답을 남겨 주세요.");return null;}const fields={sessionId:gate.sessionId,stepIndex:gate.stepIndex,takeId:gate.takeId};return guided.action(answers?"before":"view",answers?{...fields,answers,view:true}:{...fields,withoutAnswers:true,reason:"답 없이 봄"});};
  const changeParticipant=async(participant,type="select")=>{if(!await profiles.action(type,participant))return false;setTeacherGuided(false);setPracticeSetup(null);setAllParticipants(false);setSelectedTakeId(null);setReadyTake(null);setView(current=>current==="questions"?"results":current);return true;};
  const resumeGuidedSession=async session=>{setTeacherGuided(true);const participant=v24Participant(session);if(profiles.latest.current.selected!==participant){resumeAfterProfile.current=session;if(!await changeParticipant(participant))resumeAfterProfile.current=null;return;}guided.setHidden(false);await openGuidedStep(session);};
  const enterOrdinary=()=>{setTeacherGuided(false);guided.setHidden(true);setView(current=>current==="questions"?"practice":current);};
  const switchForGuidedTake=async gate=>{enterOrdinary();takeAfterProfile.current={participant:gate.participantRequired,takeId:gate.takeId};if(!await changeParticipant(gate.participantRequired))takeAfterProfile.current=null;};
  const saveGuidedAnswers=answers=>{const session=guided.activeRef.current;if(!session||v24Participant(session)!==profiles.latest.current.selected||v23StepDefinition(session)?.type!=="questions")return;return guided.action("questions",{sessionId:session.sessionId,stepIndex:session.currentStepIndex,answers});};
  const currentParticipant=profiles.snapshot.selected,sessionVisible=!guided.hidden&&(currentParticipant!=="선생님"||teacherGuided),visibleResults=v24ParticipantResults(results,currentParticipant,allParticipants);
  useEffect(()=>{setAllParticipants(false);setSelectedTakeId(null);setReadyTake(null);const target=takeAfterProfile.current;if(target&&target.participant===currentParticipant){takeAfterProfile.current=null;setSelectedTakeId(target.takeId);setView("results");}const resume=resumeAfterProfile.current;if(resume&&v24Participant(resume)===currentParticipant){resumeAfterProfile.current=null;setTeacherGuided(true);guided.setHidden(false);openGuidedStep(resume);}else if(currentParticipant==="선생님"||guided.snapshot.active&&v24Participant(guided.snapshot.active)!==currentParticipant)guided.setHidden(true);},[currentParticipant]);
  useEffect(()=>{const active=guided.snapshot.active;if(active&&v24Participant(active)!==currentParticipant){guided.setHidden(true);setView(current=>current==="questions"?"results":current);}},[currentParticipant,guided.snapshot.active?.sessionId,guided.snapshot.active?.participant,guided.snapshot.active?.participantLabel]);
  const openCalibration=()=>{setCalibrationGuide(true);setView("settings");};
  const canReturnToTraining=v19CanReturnToTraining(state,loading,shutdown.locked.current);
  const returnToTraining=()=>{if(!canReturnToTraining)return;document.querySelectorAll("audio").forEach(audio=>{audio.pause();audio.removeAttribute("src");audio.load();});window.location.assign("/");};
  if(shutdown.screen.mode!=="idle"){
    const complete=shutdown.screen.mode==="complete",failed=shutdown.screen.mode==="failed";
    return <main className="app-shell shutdown-screen"><p className="eyebrow">BASS LAB · 연습 마치기</p><section className={"result-card shutdown-card "+(complete?"complete":failed?"failed":"closing")} role={failed?"alert":"status"}><div className="shutdown-symbol" aria-hidden="true">{complete?"✓":failed?"!":"…"}</div><h1>{complete?"프로그램을 종료했습니다. 이 탭을 닫아도 됩니다":failed?"아직 종료 완료를 확인하지 못했습니다":"저장하고 종료하는 중입니다"}</h1><p>{complete?"녹음과 결과를 정리하고 장치를 해제했습니다. 이제 파일을 옮기거나 업데이트해도 됩니다.":shutdown.screen.message}</p><ol className="shutdown-steps">{v18ShutdownSteps(shutdown.lifecycle,complete).map(step=><li key={step.label} data-done={step.done}><span aria-hidden="true">{step.done?"✓":"○"}</span>{step.label}<small>{step.done?"완료":"확인 중"}</small></li>)}</ol>{complete?<div className="shutdown-next"><strong>다음 연습은 BassLab.exe를 누르면 열립니다.</strong><p>이 브라우저 탭은 위쪽 ×로 닫아 주세요.</p></div>:failed?<><p className="muted">강제로 종료하지 않았습니다. 이 화면에서 상태를 다시 확인하거나, 폴더의 STOP-BASSLAB.cmd로 종료할 수 있습니다.</p>{shutdown.screen.canCheck&&<button className="primary" onClick={shutdown.check}>종료 상태 다시 확인</button>}</>:<p className="muted">잠시만 기다려 주세요. 저장 중인 작업을 마친 뒤 프로그램을 종료합니다.</p>}</section></main>;
  }
  return <main className="app-shell"><ParticipantSwitcher profiles={profiles} engineBusy={v13Busy(state)||state.deviceReleased!==true} sessionLocked={!!guided.snapshot.active&&sessionVisible} onOrdinary={enterOrdinary} onChange={changeParticipant}/><nav aria-label="연습 메뉴로 이동"><button onClick={returnToTraining} disabled={!canReturnToTraining} title={canReturnToTraining?"다섯 훈련으로 돌아가기":"녹음·지연 측정·저장과 장치 해제가 끝나면 돌아갈 수 있습니다"}>← 연습 메뉴</button></nav><div className="program-exit-bar"><div className="exit-guidance"><strong>연습을 마칠 때</strong><span>종료 버튼을 누르거나 마지막 BassLab 탭을 닫으세요.</span><small>탭을 닫으면 10초 뒤 저장·장치 해제를 마치고 종료합니다.</small></div><button onClick={shutdown.start}>프로그램 종료</button></div><header className="app-header"><div><p className="eyebrow">BASS LAB · 함께 연습하기</p><h1>클릭과 나란히 듣고 살펴보기</h1></div><span className="version-tag">옮겨 쓰는 연습 도구</span></header><p className="lead">클릭마다 음이 어디에 놓였는지 봅니다. 지연을 잰 녹음은 클릭과 함께, 아직 재지 않은 녹음은 클릭을 끄고 들어보세요.</p>
    <div className="guided-entry">{currentParticipant==="선생님"?<details className="teacher-session-menu"><summary>메뉴</summary><button disabled={!guided.ready||guided.busy} onClick={()=>{guided.setSummaryId(null);setView("sessions");}}>검수 세션</button></details>:<button disabled={!guided.ready||guided.busy} onClick={()=>{guided.setSummaryId(null);setView("sessions");}}>검수 세션</button>}{guided.hidden&&guided.snapshot.active&&currentParticipant!=="선생님"&&<span>일반 연습 중 · 새 녹음은 세션에 묶지 않습니다.</span>}</div>
    {guided.snapshot.active&&sessionVisible&&v24Participant(guided.snapshot.active)===currentParticipant&&<GuidedSessionBanner session={guided.snapshot.active} busy={guided.busy} engineBusy={v13Busy(state)||state.deviceReleased!==true} onOpen={()=>openGuidedStep(guided.snapshot.active)} onNext={()=>nextGuidedStep(guided.snapshot.active)} onSkip={()=>skipGuidedStep(guided.snapshot.active)} onEnd={()=>endGuidedSession(guided.snapshot.active)} onHide={enterOrdinary}/>}
    <nav className="view-tabs" aria-label="화면 선택"><button className={view==="results"?"active":""} disabled={v13Busy(state)} onClick={()=>setView("results")}>녹음 결과</button><button className={view==="practice"?"active":""} disabled={v13Calibrating(state)} onClick={()=>setView("practice")}>연습</button><button className={view==="settings"?"active":""} disabled={v13Busy(state)} onClick={()=>{setCalibrationGuide(false);setView("settings");}}>장치와 지연 설정</button></nav>
    {state.startupNotice&&<p className="notice startup-notice" role="status">{state.startupNotice}</p>}
    {terminal&&<section className="notice" role="status"><strong>{state.phase==="ENDING"?"연습을 마치는 중입니다":"이 연습 세션에서는 새 녹음을 시작할 수 없습니다"}</strong><p>{v20SessionMessage(state)}</p></section>}
    {state.phase==="ANALYZING"&&<div className="analysis-banner" role="status"><strong>녹음 저장 완료 · 분석 중</strong><p>결과가 준비되면 방금 녹음한 카드가 자동으로 열립니다. 장치는 해제되어 있습니다.</p></div>}
    {readyTake&&view==="results"&&state.phase!=="ANALYZING"&&<div className="ready-banner" role="status">결과 준비됨 · 방금 저장한 녹음을 열었습니다.</div>}
    {pendingTarget.current&&["SAVED","ENDED"].includes(state.phase)&&<div className="analysis-banner" role="status"><strong>저장된 결과를 확인하고 있습니다.</strong><p>자동 확인은 세 번까지만 합니다. 계속 보이지 않으면 결과를 다시 읽어 주세요. </p><button onClick={()=>{if(resultBusy.current)return;resultAttempts.current=0;refreshResults(pendingTarget.current).catch(error=>setError(error.message));}}>결과 다시 읽기</button></div>}
    {engineError&&<div className="error-box" role="alert"><div><strong>{engineError}</strong><details><summary>오류 기록 자세히</summary><p>{state.lastError}</p></details></div><button onClick={()=>Promise.all([read("state").then(accept),refreshResults()]).catch(error=>setError(error.message))}>저장 상태 확인</button></div>}
    {error&&<div className="error-box" role="alert"><p>{error}</p><button onClick={()=>setError("")}>알림 닫기</button></div>}
    {view==="results"&&profiles.ready&&<ParticipantResultScope participant={currentParticipant} count={v24ParticipantResults(results,currentParticipant).length} all={allParticipants} onChange={setAllParticipants}/>}
    {loading||!profiles.ready?<section className="empty-panel"><h2>저장된 결과를 불러오는 중</h2></section>:view==="sessions"?<GuidedSessionPicker guided={guided} participant={currentParticipant} onStart={startGuidedSession} onResume={resumeGuidedSession} onEnd={endGuidedSession}/>:view==="questions"&&sessionVisible&&guided.snapshot.active&&v24Participant(guided.snapshot.active)===currentParticipant&&v23StepDefinition(guided.snapshot.active)?.type==="questions"?<GuidedQuestions key={guided.snapshot.active.sessionId+":"+guided.snapshot.active.currentStepIndex} session={guided.snapshot.active} busy={guided.busy} onSave={saveGuidedAnswers}/>:view==="results"&&!guided.ready?<GuidedResultGate gate={{loading:true}} busy={guided.busy} onRefresh={()=>guided.recoverPending().catch(error=>setError(error.message))}/>:view==="results"?<ObservationResults getSessionGate={result=>!guided.ready||guided.recordPending||guided.snapshot.errors?.length?{loading:true,takeId:result.takeId}:v24ProfileTakeGate(guided.latest.current,result.takeId,currentParticipant)} onSessionView={viewGuidedTake} onSessionRefresh={()=>guided.recoverPending().catch(error=>setError(error.message))} onSwitchParticipant={switchForGuidedTake} sessionBusy={guided.busy||profiles.busy} guidedListen={sessionVisible&&v24Participant(guided.snapshot.active)===currentParticipant&&v23StepDefinition(guided.snapshot.active)?.type==="listen"?guided.snapshot.active:null} onListenAnswer={async(slot,answer)=>!!await guided.action("listen",{sessionId:guided.snapshot.active.sessionId,stepIndex:guided.snapshot.active.currentStepIndex,slot,answer})} onCalibration={openCalibration} registerShutdownCleanup={shutdown.registerCleanup} results={visibleResults} selectedTakeId={selectedTakeId} onCommand={command} onRequest={request} onError={setError} onPractice={()=>{setPracticeSetup(null);setView(v13DeviceReady(settings)?"practice":"settings");}} onPracticeAgain={practiceAgain} practiceAgainAvailability={practiceAgainAvailability}/>:view==="settings"?<DeviceSettings openCalibration={calibrationGuide} settings={settings} initialDevices={deviceList} onDevices={setDeviceList} state={state} results={v24ParticipantResults(results,currentParticipant)} participant={currentParticipant} profileBusy={profiles.busy} onExportProfile={profiles.exportProfile} onSettings={setSettings} onCommand={command} onRequest={request} onError={setError}/>:<PracticeFlow participant={currentParticipant} settings={settings} onCalibration={openCalibration} key={currentParticipant+":"+(practiceSetup?.id||"ordinary")} initialConfig={practiceSetup?.config||null} registerShutdownCleanup={shutdown.registerCleanup} state={{...state,captureEnabled:state.captureEnabled&&v13DeviceReady(settings)}} tasks={tasks} onCommand={command} onError={setError} receivedAt={receivedAt}/>}
    <footer>원본 녹음을 보존합니다. 클릭에 견준 타이밍을 살펴보며 등급이나 점수를 매기지 않습니다.</footer>
  </main>;
}

