'use strict';
// Aliases are display metadata, never filesystem names or device/calibration keys.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {plain,chain,safeId}=require('./portable-state.cjs');
const need=(value,message)=>{if(!value)throw Error(message);};
function participantLabel(value='나'){need(typeof value==='string','invalid-participant');const label=value.normalize('NFC').trim();need(label&&Buffer.byteLength(label,'utf8')<=120&&!/[\u0000-\u001f\u007f]/.test(label),'invalid-participant');return label;}
const ownParticipant=value=>value===undefined||value===null?'나':participantLabel(value);
function createParticipantStore(root,{clock=Date.now,maxExportBytes=256*1024*1024}={}){
 root=path.resolve(root);plain(root,true);const dir=path.join(root,'settings');try{plain(dir,true);}catch(e){if(e.code!=='ENOENT')throw e;fs.mkdirSync(dir);plain(dir,true);}const file=path.join(dir,'participants.json');
 function read(){chain(file,root);plain(file);need(fs.statSync(file).size<=2*1024*1024,'participants-metadata-too-large');const value=JSON.parse(fs.readFileSync(file,'utf8'));need(value.schema==='basslab-participants-v1'&&Array.isArray(value.participants)&&value.participants.length>0&&value.participants.length<=100&&Array.isArray(value.requests)&&Number.isSafeInteger(value.revision),'invalid-participants-file');const labels=new Set();for(const p of value.participants){need(p&&p.label===participantLabel(p.label)&&typeof p.hidden==='boolean'&&!labels.has(p.label),'invalid-participants-file');labels.add(p.label);}need(value.participants.some(p=>p.label==='나'&&!p.hidden)&&value.participants.some(p=>p.label===value.selected&&!p.hidden),'invalid-participants-selection');return value;}
 function write(value,initial=false){chain(file,root);if(!initial)plain(file);const bytes=JSON.stringify(value,null,2)+'\n';need(Buffer.byteLength(bytes)<=2*1024*1024,'participants-metadata-too-large');const tmp=path.join(dir,'participants-'+crypto.randomUUID()+'.tmp'),fd=fs.openSync(tmp,'wx');try{fs.writeFileSync(fd,bytes);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}if(initial){try{fs.linkSync(tmp,file);}finally{fs.unlinkSync(tmp);}}else fs.renameSync(tmp,file);}
 try{plain(file);}catch(e){if(e.code!=='ENOENT')throw e;write({schema:'basslab-participants-v1',selected:'나',participants:[{label:'나',hidden:false},{label:'선생님',hidden:false}],revision:0,requests:[]},true);}
 const snapshot=()=>{const value=read();return {participants:value.participants,selected:value.selected,revision:value.revision};};
 function requireKnown(label,{hidden=false}={}){label=participantLabel(label);need(read().participants.some(p=>p.label===label&&(hidden||!p.hidden)),'participant-unavailable');return label;}
 function selected(value){const state=snapshot(),label=value===undefined?state.selected:participantLabel(value);need(label===state.selected,'participant-selection-changed');return requireKnown(label);}
 function command(action,body,{busy=false}={}){need(body&&typeof body==='object'&&!Array.isArray(body)&&typeof body.participant==='string'&&Object.keys(body).every(k=>['requestId','participant',...(action==='hide'?['hidden']:[])].includes(k)),'invalid-participant-fields');need(typeof body.requestId==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(body.requestId)&&['select','add','hide'].includes(action),'invalid-participant-command');const label=participantLabel(body.participant),value=read(),fingerprint=JSON.stringify({action,participant:label,...(action==='hide'?{hidden:body.hidden}:{} )}),prior=value.requests.find(r=>r.requestId===body.requestId);if(prior){need(prior.fingerprint===fingerprint,'request-id-content-mismatch');return snapshot();}need(!busy,'participant-change-while-busy');need(value.requests.length<8000,'participant-change-history-full');const existing=value.participants.find(p=>p.label===label);
  if(action==='add'){need(!existing,'participant-already-exists');need(value.participants.length<100,'participant-limit');value.participants.push({label,hidden:false});value.selected=label;}
  else if(action==='select'){need(existing&&!existing.hidden,'participant-unavailable');value.selected=label;}
  else{need(existing&&typeof body.hidden==='boolean','invalid-participant-hide');need(label!=='나'||body.hidden===false,'default-participant-required');existing.hidden=body.hidden;if(existing.hidden&&value.selected===label)value.selected='나';}
  value.revision++;value.requests.push({requestId:body.requestId,fingerprint,at:new Date(clock()).toISOString()});write(value);return snapshot();
 }
 function takeOwner(takeId,fallback){need(safeId(takeId),'invalid-participant-take-id');const run=path.join(root,'takes',takeId,'run.json');try{chain(run,root);need(plain(run).size<=4*1024*1024,'take-metadata-too-large');const value=JSON.parse(fs.readFileSync(run,'utf8'));need(value.takeId===takeId,'take-metadata-id-mismatch');return ownParticipant(value.participant);}catch(e){if(e.code==='ENOENT')return ownParticipant(fallback);throw e;}}
 function takeIds(participant){const selected=participantLabel(participant),takes=path.join(root,'takes'),values=[];chain(takes,root);plain(takes,true);for(const takeId of fs.readdirSync(takes)){if(!safeId(takeId))continue;const run=path.join(takes,takeId,'run.json');try{chain(run,root);plain(run);}catch(e){if(e.code==='ENOENT')continue;throw e;}if(takeOwner(takeId)===selected)values.push(takeId);}return values.sort();}
 function exportZip(body,sessions){need(body&&typeof body==='object'&&!Array.isArray(body)&&Object.keys(body).every(k=>['participant','includePcm'].includes(k))&&(body.includePcm===undefined||typeof body.includePcm==='boolean'),'invalid-participant-export');const participant=requireKnown(body.participant,{hidden:true}),ids=takeIds(participant),includePcm=body.includePcm!==false,{createSessionArchive}=require('./session-store.cjs'),archive=createSessionArchive(root,{maxExportBytes,errorPrefix:'participant-export'}),all=sessions.list();need(!all.errors.length,'session-history-unreadable');const ownedSessions=all.sessions.filter(s=>s.participant===participant),createdAt=new Date(clock()).toISOString();
  for(const takeId of ids)archive.addTake(takeId,includePcm);
  for(const session of ownedSessions)for(const name of ['session.jsonl','script.json']){const relative='sessions/'+session.sessionId+'/'+name;archive.add(path.join(root,relative),relative);}
  archive.addBytes('PROFILE.json',JSON.stringify({schema:'basslab-participant-profile-v1',participant,version:'26',portableVersion:26,takeCount:ids.length,sessionCount:ownedSessions.length,createdAt},null,2)+'\n');
  return archive.finish({schema:'basslab-participant-export-v1',participant,version:'26',portableVersion:26,takeIds:ids,sessionIds:ownedSessions.map(s=>s.sessionId),includePcm,createdAt,noEngineLogs:true,otherParticipantsAudioIncluded:false});
 }
 return {snapshot,command,requireKnown,selected,takeOwner,takeIds,exportZip};
}
module.exports={createParticipantStore,participantLabel,ownParticipant};
